### ISSUE TITLE
Deprecation : user_identity_field - improve defaults or deprecation message

### ISSUE THREAD

**Issue by EvilSpartans** [lexik/LexikJWTAuthenticationBundle#1051] opened 2022-07-29 11:37 UTC
Hello, I have updated my project to symfony 6, and now with this config I have a warning error in the console : 

```
lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 604800
  user_identity_field: email
```

**deprecation.INFO: User Deprecated: Since lexik/jwt-authentication-bundle 2.5: The "lexik_jwt_authentication.user_identity_field" configuration key is deprecated since version 2.15, implement "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()" instead.**

If I remove this user_identity_field from the config file, when I login to the api and copy paste the token to secure url, I have a 401 error : jwt not found. So I don't know what to do ?

Here is my security file : 

```
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    registration:
      pattern: ^/api/users
      stateless: true
      methods: [POST]

    login:
      pattern: ^/api/login
      # user_checker: App\Security\UserChecker
      stateless: true
      json_login:
        username_path: email
        password_path: password
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
```

Thanks for your help ! The warning in the console is annoying ...

**Comment by fd6130** [comment] 2022-07-29 12:03
Just curious about the ` 401 error : jwt not found`.  Double check your request header if it really contains the Bearer Token header?

And are you using Apache web server? Try take a look at this docs: https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/index.html#important-note-for-apache-users

**Comment by EvilSpartans** [comment] 2022-07-29 12:05
@fd6130 Hello, yes I just take a look : 
![image](https://user-images.githubusercontent.com/50326257/181754843-e144e35c-c3e3-4028-8a42-7f24249621ab.png)
and yes I'm using apache

**Comment by chalasr** [comment] 2022-07-29 14:01
Does your `User::getUserIdentifier()` method return the `email` property?

**Comment by EvilSpartans** [comment] 2022-07-29 14:03
@chalasr  yes : 

```    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
```

**Comment by EvilSpartans** [comment] 2022-07-29 17:24
So I finally found a solution (with help), I share it to help people who have the same problem.

First you must check you have the getUserIdentifier() method in User.php entity : 
```
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
```
then, don't forget to **remove the old getUserName() method** ! It was the problem with me. I use instead getFullName() (just rename getUsername to getFullName). And if you are using this username for front end app, you can add a ```#[SerializedName('username')]``` to don't have to make changes.

And finally, you can remove the user_identifier_field from the lexik config file : 
```
lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 604800
```

**Comment by JorickPepin** [comment] 2022-07-30 06:47
@EvilSpartans, you may want to add `user_id_claim: email` in the configuration file so that the name of the key in the token payload remains email and is not replaced by the default value which is username. This was done automatically with `user_identity_field: email`.

**Comment by chalasr** [comment] 2022-07-30 22:46
>  don't forget to remove the old getUserName() method ! It was the problem with me. I

Reopening then, I think we can improve the situation.
The same goes for @JorickPepin's hint, it's easy to miss doing that and probably annoying to debug so if we should fix it, or at least make the deprecation message suggest it so that one we get the full upgrade path.

**Comment by EvilSpartans** [comment] 2022-07-30 22:48
> @EvilSpartans, you may want to add `user_id_claim: email` in the configuration file so that the name of the key in the token payload remains email and is not replaced by the default value which is username. This was done automatically with `user_identity_field: email`.

This was not working, I already tried before ask for help :)

**Comment by fd6130** [comment] 2022-07-31 02:40
Hmmm so if we have `getUsername()` and `getUserIdentifier()` both in a user provider, it will trigger the `401 JWT Not Found` ?

**Comment by EvilSpartans** [comment] 2022-07-31 05:46
> Hmmm so if we have `getUsername()` and `getUserIdentifier()` both in a user provider, it will trigger the `401 JWT Not Found` ?

Without get_user_identifier_field in config file yes, for secure url. But with identifier_field you will have deprecation notices in the prod console.

**Comment by fd6130** [comment] 2022-07-31 06:26
> > don't forget to remove the old getUserName() method ! It was the problem with me. I
> 
> Reopening then, I think we can improve the situation. The same goes for @JorickPepin's hint, it's easy to miss doing that and probably annoying to debug so if we should fix it, or at least make the deprecation message suggest it so that one we get the full upgrade path.

So the problem is, user might not know that the symfony `UserInterface` already deprecate `getUsername()`  right? Because once we know about the deprecation in `UserInterface`, the deprecation message in this bundle looks fine to me:

> deprecation.INFO: User Deprecated: Since lexik/jwt-authentication-bundle 2.5: The "lexik_jwt_authentication.user_identity_field" configuration key is deprecated since version 2.15, implement "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()" instead.

Might be because we user just upgrade the library without looking at the changelog first.

**Comment by Jean85** [comment] 2022-09-05 15:49
I just stumbled in this same exact problem. I'm on SF 5.4 and I wanted to get rid of this exact deprecation.

To fix it I removed the `user_identity_field: token` setting, and reworked my custom user like this:
```php
class FrontendUser extends JWTUser
{
    public static function createFromPayload($username, array $payload): self
    {
        return parent::createFromPayload($payload['token'], $payload);
    }
}
```

This should've been enough to fix it, but it's currently failing because of this piece of code: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/d7cbef600712eb57af7cafd28130985553b50b37/Security/Authenticator/JWTAuthenticator.php#L120-L123

I could send a PR to skip this piece if `$idClaim === null`, but the config doesn't accept `null` as a value; also, `UserInterface::getUserIdentifier` could be called only afterwards the user is already fetched which, depending on the config, could involve a DB query.

So... how can we solve this?

**Comment by JorickPepin** [comment] 2022-09-07 11:39
@Jean85, did you try to add `user_id_claim: token` in the configuration file? See [this comment](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1051#issuecomment-1200103704).

**Comment by Jean85** [comment] 2022-09-07 12:31
It worked, thanks! So, this issue could be fixed by changing the deprecation message from
> The "lexik_jwt_authentication.user_identity_field" configuration key is deprecated since version 2.15, implement "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()" instead.

to

> The "lexik_jwt_authentication.user_identity_field" configuration key is deprecated since version 2.15, use "lexik_jwt_authentication.user_id_claim" or implement "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()" instead.

right?

**Closed as completed** 2022-10-09 20:23 UTC
Labels: Bug, help wanted

**Comment by lermontex** [comment] 2023-03-05 22:44
@chalasr, @JorickPepin,  @Jean85, 

> @EvilSpartans, you may want to add user_id_claim: email in the configuration file so that the name of the key in the token payload remains email and is not replaced by the default value which is username. This was done automatically with user_identity_field: email.

It may break the application. The fact is that `user_identity_field` !== `user_id_claim`

Please see issue #1083

**Comment by ssj17vegeta** [comment] 2025-11-10 13:32
Just a very late comment to thank @EvilSpartans who saved me hours of fruitless search : I had a similar issue where I had created a userName property in my User entity, and didn't know it messed up JWT authentication with API Platform ! Thanks, I would *never* have thought of that !

**Comment by EvilSpartans** [comment] 2025-11-10 13:40
@ssj17vegeta You're welcome if I was able to help you.
