### ISSUE TITLE
Invalid JWT token

### ISSUE THREAD

**Issue by AlexSanzharevskyy** [lexik/LexikJWTAuthenticationBundle#199] opened 2016-07-18 19:16 UTC
Hi there! Trying for a few days to resolve the next error - 403 Forbidden, Invalid JWT roken. I set the rewrite rules, but it doesn't work. I've created JWTInvalidListener, and modified the response to see the the event, but it's empty - attributes:{}, cookies:{}, files:{}, headers:{}, query:{}, request:{}, server:{}. Any suggestions? Thanks in advance!

**Comment by chalasr** [comment] 2016-07-18 21:10
Hello @AlexSanzharevskyy 

> I've created JWTInvalidListener, and modified the response to see the the event, but it's empty - attributes:{}, cookies:{}, files:{}, headers:{}, query:{}, request:{}, server:{}. 

All the empty objects listed are part of the Request (i.e. `JWTinvalidEvent::getRequest()`), not the Response (i.e. `JWTInvalidvent::getResponse()`). Is it a mistake?

Is it the first time you use the bundle ? Or is it something that worked before and broke recently?
How are you sending the token to your server (i.e. header, query..) ?

Also by

> 403 Forbidden, Invalid JWT roken

I guess you mean 401 Unauthorized, right?

**Comment by AlexSanzharevskyy** [comment] 2016-07-19 06:18
oh, sorry, forgot the details. Yes, it's the first time i'm using JWT Lexik Bundle, also i'm using Symfony 3.0.6, as the frontend - Angular app, and there is an interceptor, which attaches Authorization Bearer header. Login goes successfully, but then i get en error. And yes, it returns 401 not 403. In security.yml i set to retrieve token from cookies, now i have 401 with 'Invalid credentials' message. I tried OSX and Win10 configuration. Thanks!

**Comment by chalasr** [comment] 2016-07-19 23:20
> ... an interceptor, which attaches Authorization Bearer header ...
... i set to retrieve token from cookies...

If you are setting the token as header, you must retrieve the token from the headers, not the cookies. The `authorization_header` is enabled by default, if you disabled it, you must enable it, please refer to the documentation for that.

Once the `authorization_header` is enabled in your `lexik_jwt` secured firewall, you should verify that the header is correctly sent to your server, by dumping the request headers from your controller for instance, and verify it contains a valid token.

To verify the token, you can do that from your CLI:

```
curl -H "Authorization: Bearer [token here]" http://localhost:8000/api/[resource]
```

Replacing `http://localhost:8000/api/[resource]` by a secured route.

If the header is not sent, the issue is related to your usage of the "interceptor" attaching your token in headers.

I close the issue, please let us know if the problem persists out of your frontend tool.

**Closed by chalasr** 2016-07-19 23:20 UTC
