### ISSUE TITLE
Moving token from body to header

### ISSUE THREAD

**Issue by IljaN** [lexik/LexikJWTAuthenticationBundle#313] opened 2017-03-08 17:57 UTC
I would like to have the token which is returned after login, to be returned in the header instead of the body.

I created a AuthenticationSuccessListener, but can`t overide the body to make it empty. Is this intentional?
```php
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event) {
        $data = $event->getData();

        if (!$event->getUser() instanceof UserInterface) {
            return;
        }

        $response = $event->getResponse();
        $response->headers->add(['authorization' => $data['token']]); // works
        $response->setContent(''); // no effect
        $event->setData([]); // no effect
    }
```

**Comment by chalasr** [comment] 2017-03-09 20:04
This is the expected behavior indeed, but that's because we didnot see any valid use case at the moment it has been implemented. I'll have a look at what we can do, maybe this event deserves a `setResponse()` as well.

**Comment by IljaN** [comment] 2017-03-09 21:07
My usecase is that for example vue-auth defaults to reading the token from the header after login. I googled and found some other jwt implementations that also behave like that altough they seem to be in the minority.

**Comment by chalasr** [comment] 2017-03-30 12:05
Fixed by #320

**Closed by chalasr** 2017-03-30 12:05 UTC
Labels: Feature

**Comment by IljaN** [comment] 2017-03-31 11:02
@Batch1211 Thank you very much! <3
