### ISSUE TITLE
use another type of secret token

### ISSUE THREAD

**Issue by fcpauldiaz** [lexik/LexikJWTAuthenticationBundle#463] opened 2018-02-26 20:18 UTC
is it possible to use another secret token that is not a .pem file ? Something like an .env var?
Related to #24

**Comment by chalasr** [comment] 2018-02-27 14:30
Duplicate of https://github.com/lexik/LexikJWTAuthenticationBundle/issues/340?

**Comment by chalasr** [comment] 2018-03-04 14:42
Closing in favor of #340

**Closed by chalasr** 2018-03-04 14:42 UTC
