### ISSUE TITLE
InvalidArgumentException : The token is an invalid JWS

### ISSUE THREAD

**Issue by Boulboulouboule** [lexik/LexikJWTAuthenticationBundle#327] opened 2017-04-27 15:00 UTC
Hi !

I'm encountering an issue installing my project on a new environnement. Everything works well with 2 others environnements, but with this one it fails... :(

The token is successfully generated, but I can't use it, it looks like it can't be decoded.
Here're the logs : 
```
[2017-04-27 14:53:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-04-27 14:53:28] request.CRITICAL: Uncaught PHP Exception Lexik\Bundle\JWTAuthenticationBundle\Exception\JWTDecodeFailureException: "Invalid JWT Token" at /var/www/html/nuages/api/vendor/lexik/jwt-authentication-bundle/Encoder/DefaultEncoder.php line 55 {"exception":"[object] (Lexik\\Bundle\\JWTAuthenticationBundle\\Exception\\JWTDecodeFailureException(code: 0): Invalid JWT Token at /var/www/html/nuages/api/vendor/lexik/jwt-authentication-bundle/Encoder/DefaultEncoder.php:55, InvalidArgumentException(code: 0): The token \"\" is an invalid JWS at /var/www/html/nuages/api/vendor/namshi/jose/src/Namshi/JOSE/JWS.php:143)"} []
```

Do you have any clue ?

Thanks for the help !

**Comment by chalasr** [comment] 2017-04-27 15:16
Hi @Boulboulouboule

This issue would be better asked a stackoverflow since it is not a bug regarding this bundle but a platform issue. Now that you're here, let's try to know what happens.

I suggest you to `var_dump()` the token once it is created (f.e. by dumping this line: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/DefaultEncoder.php#L44), put it in your clipboard and then `var_dump()` the token when your server decodes it (f.e. by dumping `$token` before this line https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/DefaultEncoder.php#L52 when trying to make a JWT authenticated request). 
Then, compare the first dumped token (created) with the second one (received) to see if they look the same. If they don't, something mangles your token, that's probably apache.

Also if you're using apache, makes sure that `mod_rewrite` is enabled on your server and take a look at this note https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users.

**Comment by Boulboulouboule** [comment] 2017-04-27 16:46
Hi @chalasr ! 

> This issue would be better asked a stackoverflow since it is not a bug regarding this bundle but a platform issue. Now that you're here, let's try to know what happens.

Yes it's true, sorry and thank you for giving me a part of your time despite it.

> I suggest you to var_dump() the token once it is created (f.e. by dumping this line: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/DefaultEncoder.php#L44), put it in your clipboard and then var_dump() the token when your server decodes it (f.e. by dumping $token before this line https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/DefaultEncoder.php#L52 when trying to make a JWT authenticated request).

I did it ! And the dump return me `false` inside the decode() function each time in the production environment. It's weird, on my local environment the dump is returning me the token..!

I can't figure out what is causing this issue, do you have any idea ?

**Comment by chalasr** [comment] 2017-04-27 16:52
@Boulboulouboule I think you're running into this issue https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users

**Comment by Boulboulouboule** [comment] 2017-04-27 16:55
@chalasr I checked and added it in the .htaccess before posting the issue, but it still doesn't works  :/

**Comment by chalasr** [comment] 2017-05-02 07:59
You're welcome, closing as resolved then.

**Closed by chalasr** 2017-05-02 07:59 UTC
Labels: Question
