### ISSUE TITLE
{"code":401,"message":"JWT Token not found"}

### ISSUE THREAD

**Issue by Lawrancecool** [lexik/LexikJWTAuthenticationBundle#268] opened 2016-11-08 06:22 UTC
<VirtualHost *:80>
        ServerName angulartest
        ServerAdmin ssiplrobert@localhost
        DocumentRoot /home/robert/Projects/ServerProjects/Projects/Angular2Symfony/web/
        ErrorLog ${APACHE_LOG_DIR}/angulartest_error.log
        CustomLog ${APACHE_LOG_DIR}/angulartest_access.log combined
        <Directory /home/robert/Projects/ServerProjects/Projects/Angular2Symfony/web/ >
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                Allow from all
                Require all granted

                RewriteEngine on
                RewriteCond %{HTTP:Authorization} ^(.*)
                RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
                RewriteCond %{REQUEST_FILENAME} -s [OR]
                RewriteCond %{REQUEST_FILENAME} -l [OR]
                RewriteCond %{REQUEST_FILENAME} -d
                RewriteRule ^.*$ - [NC,L]
                RewriteRule ^(.*) /index.html [NC,L]
        </Directory>

Request URL:http://angulartest/app_dev.php/api/login_check
Request Method:POST
Status Code:401 Unauthorized

Remote Address:127.0.0.1:80
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:49
content-type:application/json
Host:angulartest
Origin:http://angulartest
Referer:http://angulartest/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
{username: "Test", password: "Star123"}
                                                                                                                                 36,1          Top

**Comment by chalasr** [comment] 2016-11-08 08:21
Hi @Lawrancecool,

This looks like a configuration issue, still.
Would you consider forking https://github.com/chalasr/lexik-jwt-authentication-sandbox for reproducing it? So we could investigate directly.
Or you can [open a question on stackoverflow](https://github.com/lexik/LexikJWTAuthenticationBundle#support), so you get more chance that someone solve your issue.

**Comment by Lawrancecool** [comment] 2016-11-08 09:11
Yes i configure like https://github.com/chalasr/lexik-jwt-authentication-sandbox that only

**Comment by chalasr** [comment] 2016-11-08 09:13
If you mind to fork this repository then reproduce your exact issue and give me the url of your fork, then I can give it a try. Otherwise, please open a question on stackoverflow. This is a support issue about symfony or your webserver, but not a bug on this bundle.

**Comment by Lawrancecool** [comment] 2016-11-08 09:23
Okay i will give fork url

**Comment by Lawrancecool** [comment] 2016-11-08 09:26
How to i can customise url  paramerters and respone 
curl -X POST http://localhost:8000/login_check -d _username=johndoe -d _password=test
now only give token only how i can customise that respone

**Comment by Lawrancecool** [comment] 2016-11-08 09:50
when i post through curl its work web server
    i got like that
                         body: "{"code":401,"message":"Bad credentials"}", status: 401, ok: false, statusText: "Unauthorized", headers: Headers…}

**Comment by chalasr** [comment] 2016-11-08 09:55
> How to i can customise url paramerters

This is __not__ related to this bundle, see http://symfony.com/doc/current/reference/configuration/security.html#username-parameter

> and response

Please read the doc, we provide full examples of how customizing the response and lots of other stuff. See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md

I'm closing this issue as it is about support, which should be done on stackoverflow where everyone can see how to solve the same problem, please see https://github.com/lexik/LexikJWTAuthenticationBundle#support for your next support questions.

**Closed by chalasr** 2016-11-08 09:55 UTC
