### ISSUE TITLE
Database-less user provider empty payload

### ISSUE THREAD

**Issue by xhuberdeau** [lexik/LexikJWTAuthenticationBundle#392] opened 2017-09-25 13:26 UTC
Hi,
I'm using the database-less user provider ([https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md)) with a custom user class implementing JWTUserInterface. The problem is that the payload array is empty in the createFromPayload method. So I can't create a new user as I don't have the required data (in the payload) to do so.

I have added some custom data in the payload via the JWTCreatedListener class. When I log in, I receive the json token. When I parse it on JWT.IO, all my information are here. So I'm sure everything is fine at the token creation.

Any idea ?

[Edit] : As a workaround, I wrote my own JWTTokenAuthenticator in which the payload was complete. So from this point I was able to return directly my custom User based on the payload data (in the loadUser method).

**Comment by chalasr** [comment] 2017-10-06 12:52
I will look into this as soon as possible.

**Comment by alfredvaa** [comment] 2018-05-14 20:47
Any progress? I experience the same thing

**Comment by sefaYavuz** [comment] 2020-03-23 10:59
@chalasr Any progress?

**Comment by Vyaza** [comment] 2020-09-17 07:03
Had the same problem, found out that it was caused by using jwt with custom payload as part of a chain user provider. Luckily, the issue has been already fixed in more recent versions of the bundle. If anyone else came here for solution - just update the bundle to something like 2.8.0 or later.

**Closed** 2023-12-02 21:21 UTC
Labels: Bug, Needs Review
