### ISSUE TITLE
JWT:  invalid signature

### ISSUE THREAD

**Issue by TheFlow95** [lexik/LexikJWTAuthenticationBundle#68] opened 2015-05-30 16:22 UTC
Hello,

When I paste the token received with the login_check uri in [jwt.io](http://jwt.io), it says that the signature is invalid, is it normal ?

**Comment by carlcraig** [comment] 2015-05-30 18:51
jwt.io only supports hs256 and rs256 jwt. so f the token you are generating is different alg then it will be invalid on jwt.io.

try pasting the token using rs256 in jwt.io, and then paste the public and private keys.

**Comment by TheFlow95** [comment] 2015-05-30 19:00
It's already in RS256 because of the header of the token

**Comment by carlcraig** [comment] 2015-05-30 19:04
oki, did you paste the public/private keys into fields? i havent tried jwt.io rs feature yet, so not sure how well it works.

**Comment by TheFlow95** [comment] 2015-05-30 19:18
When I paste the keys, nothing change

**Comment by carlcraig** [comment] 2015-05-30 19:45
i have no clue then, is most likely an issue with jwt.io

**Comment by TheFlow95** [comment] 2015-05-30 19:58
Is it not a problem of the token ?

**Comment by slashfan** [comment] 2015-06-02 09:51
I tested using only the namshi/jose library and the result is the same. We'll have to investigate what is the problem, the library or the jwt.io decoding. Anyway, it is not really a problem for the moment.

**Comment by TheFlow95** [comment] 2015-06-02 09:56
Thank you, I reported it just for you to know

**Comment by slashfan** [comment] 2015-06-02 09:57
That's cool, I'll try to find the cause of the problem.

**Closed** 2015-06-02 11:05 UTC

**Comment by bryanbecker** [comment] 2015-07-03 14:33
Is there any update on this?

I'm having the same issue

**Comment by olabb** [comment] 2016-06-23 07:14
in the verify signature column, fill in your secret

**Comment by raesteyn** [comment] 2016-06-29 11:14
If anyone is still running into this issue, what sorted it for me was to change the secret to match my key, then paste the token in again.

pasting the token in AFTER changing the secret is the crux of what got mine to verify.

I was using HS256.
