### ISSUE TITLE
php8 compatibility 

### ISSUE THREAD

**Issue by mitalcoi** [lexik/LexikJWTAuthenticationBundle#793] opened 2020-11-22 21:05 UTC
After updating to php 8 I got that strange error in tests:
`InvalidArgumentException: It was not possible to parse your key, reason: 
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:90
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:47
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:21
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Signer/BaseSigner.php:36
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Builder.php:470
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lcobucci/jwt/src/Builder.php:450
/builds/riverwaysoft/rebelbee/phonedo_project/phonedo/vendor/lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php:99`
Reason of error is empty.

Problem pointed here:
<img width="866" alt="Снимок экрана 2020-11-23 в 00 05 05" src="https://user-images.githubusercontent.com/3224226/99917153-8bf11200-2d1f-11eb-83c9-9fe94deac023.png">

**Comment by chalasr** [comment] 2020-11-23 09:58
Hey, 

I'm working on the PHP 8 support. I'll keep you informed.

**Comment by mikface** [comment] 2020-11-27 08:38
@chalasr @mitalcoi 
Issue is caused by resource to object migration, see [https://php.watch/versions/8.0/OpenSSL-resource](https://php.watch/versions/8.0/OpenSSL-resource)
It has been fixed in lcobucci/jwt in version 4.0.0 ([https://github.com/lcobucci/jwt/pull/431](https://github.com/lcobucci/jwt/pull/431))
So maybe just update composer.json `lcobucci/jwt` to v4?

**Comment by mitalcoi** [comment] 2020-11-27 08:50
Looks like it is already resolved here: https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.10.0

**Comment by mitalcoi** [comment] 2020-11-27 09:33
Just updated to 2.10.0 - it did't help 

lcobucci/jwt v 4.0.0 cannot be installed locally, it is also locked:  (lexik/jwt-authentication-bundle v2.10.0 requires lcobucci/jwt ^3.2 -> found lcobucci/jwt[3.2.0, ..., 3.4.1] but it conflicts with your root composer.json require (^4.0.0))

**Comment by mikface** [comment] 2020-11-27 09:35
@mitalcoi 
Yp, because in this repo in composer.json it still states "`lcobucci/jwt": "^3.2"`

**Comment by mitalcoi** [comment] 2020-11-27 09:47
@chalasr can you update composer.json with actual version lcobucci/jwt?

**Comment by chalasr** [comment] 2020-11-27 10:57
We need to make the bundle compatible with lcobucci/jwt v3.4 first. 
Should be resolved quickly, I'm going to look at it this weekend.

**Comment by samijnih** [comment] 2020-11-28 03:17
Only cow I've found the same trouble with `OpenSSLAsymmetricKey` class instead of resource. I wish I could had see this issue early instead of "wasting" time :joy: 

Can't wait to see a fix! :) :muscle:

**Comment by Kyngo** [comment] 2021-10-03 17:29
Not sure if this is already working...? 🤔 I can't seem to be able to install this bundle using PHP 8...
EDIT: Nope, my fault, php-mbstring was not installed.

**Comment by chalasr** [comment] 2021-10-03 17:30
Please provide some details about the issues you are facing.

**Comment by Kyngo** [comment] 2021-10-03 17:37
Like I said, it was my fault. Not reading properly the composer error logs... It was clearly saying that the php-mbstring module was missing. Installing it solved the issue.

**Comment by chalasr** [comment] 2021-10-03 17:38
Missed your edit. All good then 👌

**Closed by chalasr** 2021-10-03 17:38 UTC
