### ISSUE TITLE
JSONWebToken Token naming 

### ISSUE THREAD

**Issue by Ahummeling** [lexik/LexikJWTAuthenticationBundle#1122] opened 2023-02-22 20:30 UTC
First of all, thank you very much for this awesome bundle!

I came across a very straight forward exception message, and got a little annoyed with the wording:
```json
{
  "code": 401,
  "message": "JWT Token not found"
}
```

The T in JWT stands for Token, so this reads out to "JSON Web Token Token not found". In my native language, this is considered a grammatical error, I am not sure if this is the case in english. More importantly, I am even less sure about whether this naming might've been intentional. 

I wanted to submit a PR that "fixes" the occurrences of JWT Token by renaming them to JWT where it makes sense to do so. But I wanted to check first that such a PR would be appreciated in the first place.

Again thanks for the awesome bundle, I'm hoping to make it ever so slightly better.

**Comment by Bryce-Colton** [comment] 2023-11-25 08:27
In my view, the acronym 'JWT' works well – a quick way to convey or refer to what you're talking about. In France, everyone says 'JWT token' in French conversations.

If you wish to make improvements, kindly provide a configuration option for the default error message. That way, everyone will be satisfied :)

**Comment by Bryce-Colton** [comment] 2023-11-25 08:31
Same open issue here : https://github.com/lexik/LexikJWTAuthenticationBundle/issues/983#issue-1119596113

**Comment by chalasr** [comment] 2024-12-14 15:48
Short answer: this si due to backward compatibility that needs to be preserved. I hope we'll avoid the extra `Token` at some point. Closing as duplicate of #983. Thanks

**Closed as completed by chalasr** 2024-12-14 15:48 UTC
