### ISSUE TITLE
fosrest exception wrapper handler

### ISSUE THREAD

**Issue by stickyhands** [lexik/LexikJWTAuthenticationBundle#153] opened 2016-03-30 23:17 UTC
Im using the jwt auth bundle side by side with the fos rest bundle,
I created my own exception wrapper handler to format my errors the way I want.

But I cant figure out how to intercept `{"code":401,"message":"Invalid JWT Token"}` which is supposed to be a `Symfony\Component\Security\Core\Exception\AuthenticationException`

**Comment by chalasr** [comment] 2016-04-01 21:06
This seems to be not supported for now.

If this feature come to be planed, I think the logic way would be to listen on the  `on_authentication_failure` (like implemented for the `on_authentication_successs` event, see [EVENTS::AUTHENTICATION_SUCESS Customization])(https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsauthentication_success---add-public-data-to-the-jwt-response).

@slashfan What do you think about this ? Do you know more ?

**Comment by slashfan** [comment] 2016-04-02 10:24
Hi, I don't really have time right now but I'm it is indeed an important feature for an API. 
What's your opinion @chalasr ? How would you implement that ?

**Comment by chalasr** [comment] 2016-04-03 13:53
@slashfan After a lot of tries, I just come to make it works using events.
I have a ready patch, but I would like to discuss with you before submit a PR.

First, I created an `Events::AUTHENTICATION_FAILURE` with a `$message` property that represents the `message` field of the Response body (i.e. `Bad credentials` by default).
Users can create a listener and subscribe this event such as done for the `Events::AUTHENTICATION_SUCCESS`, then call `AuthenticationFailureEvent::setMessage('custom failure message')`. The primary goal is to allow users to subscribe to this event in order to do custom stuffs in their application, customizing the response is a kind of bonus, and not very risky because changing the response itself is not possible (no `AuthenticationFailureEvent::setResponse` method).

Then, to answer this issue and make user able to subscribe on the "Invalid JWT Token" (which is not an authentication from credentials but from token), my first idea was to simply pass the authenticationFailureHandler to our JWTListener and call onAuthenticationFailure (so dispatch the same `AUTHENTICATION_FAILURE` than on invalid username/password credentials).
It worked well, but the problem is that users can't make a difference between the authentication failure from credentials and the one from invalid token, and so cannot return a different response depending on the use case.

So I created a second event called `Events::JWT_INVALID`.
Then, in `JWTListener::handle()`, when an AuthenticationException is catch, rather than return a response and stop the GetResponseEvent propagation, I made the catch dispatching the `JWT_INVALID` event, in order to allow users to subscribe on this specific event and also modify the response message, like done in the `AUTHENTICATION_FAILURE`.

Now it works well, users can subscribe on the two events and set a different custom message on the two.
My question is quite simple, what do you think about this? Do you see any downside?

Then, do you prefer that I submit two different PRs to propose each event respectively?
Separate in two would involves some additional work for me (rollback), because I created the two and adapted the tests+doc as long as it evolved, my bad.

I also added an example for each new event in the doc.
If the PR is merged, I think it could be good to add a working example for the two in the bundle sandbox.

You can see the changes by looking at my [patch_jwtinvalid_event](https://github.com/chalasr/LexikJWTAuthenticationBundle/commit/a6f917ad1c16852f485b778e427064f16805b1a1) branch.

Please keep me informed.

**Comment by slashfan** [comment] 2016-04-04 12:19
@chalasr this is very good work you just did ! 

I am perfectly OK to use events, the bundle already has a few and it's a great way to customize application behavior. My only concern is about possible BC breaks. Athough it may be dirtier, it might be safer to inject the EventDispatcher in the JWTListener through a setter for now. What do you think ?

Other than that it's OK to do only one PR, besides you already updated the tests and the docs.

**Comment by chalasr** [comment] 2016-04-04 12:53
@slashfan Totally agreed for the setter, more secure, I'll do the changes before submit the PR.

One last question, I used a `setMessage` rather than a `setResponse` in the two events in order to be sure that the responses will stay failure responses by following the default implementation (JsonResponse, 401 status and generic code+message body).
What do you think about this ? Should we give more flexibility by adding a `setResponse` or a `setData` like done in the AuthenticationSuccessEvent ? This can be easily changed.

**Comment by slashfan** [comment] 2016-04-04 18:36
Indeed it would be way more flexible if the entire response could be modified. Adding headers, changing error code or data structure... 

Adding a setResponse method on those events should suffice, as long as it enforces a Response object and doesn't accept a null argument. And maybe remove the setMessage methods so it is more clear for the user ?

**Comment by chalasr** [comment] 2016-04-04 19:31
Ok for replace the `setMessage` by a `setResponse`, I submit it when it's done.

**Comment by slashfan** [comment] 2016-04-11 08:22
@stickyhands did #157 resolved it ?

**Closed** 2016-04-18 15:29 UTC
