### ISSUE TITLE
No returned user in payload

### ISSUE THREAD

**Issue by robhunt3r** [lexik/LexikJWTAuthenticationBundle#335] opened 2017-05-11 13:19 UTC
```
    /**
     * @param AuthenticationSuccessEvent $event
     */
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $payload = $event->getData();
        $user = $event->getUser();

        if (!$user instanceof User) {
            return;
        }

        $payload['user'] = $user;

        $event->setData($payload);
    }
```

The response in my app contains `token` and `user` keys but `user` is empty, if I debug it, `$user` is indeed an `User` otherwise the condition above would trigger (and it doesn't)

If I return `$payload['user'] = $user->getId()` it is returning the id...

Why is this happening?

**Comment by chalasr** [comment] 2017-05-11 13:38
It happens because you are giving your whole User object to the payload, and `json_encode` doesn't know how to represent it (you can try it out `json_encode(['user' => $user]) ===  "{"user":{}}"`).

Normalize your object as an array of `'property' => $user->getProperty()` instead (can be done via [the symfony serializer]()), or teach `json_encode` how to represent your User object by making it implement [`\JsonSerializable`](http://php.net/manual/en/class.jsonserializable.php).

Closing here as this is the expected behavior, please tell me if my answer doesn't help you.

**Closed by chalasr** 2017-05-11 13:38 UTC
Labels: Question

**Comment by hiromik** [comment] 2017-09-20 16:33
@chalasr Using [JMS Serializer](https://github.com/schmittjoh/serializer) (or Symfony serializer) the User object is properly serialized but the second json_encode pass adds slashes to the serialized user key such as 
```json
{
  "user": "{\"type\":\"collaborator\",\"id\":16,\"nom\":\"chalas\",\"prenom\":\"robin\",\"creeLe\":\"2017-09-05T14:07:13+02:00\"}",
  "numero": "chalas",
  "iat": 1505924454,
  "exp": 1505948454
}
```
Any tips ?

**Comment by Spomky** [comment] 2017-09-20 18:35
Hi,

I thinl you can try to change the configuration of the JMSSerializerBundle.
See http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#extension-reference and the `options` parameter

**Comment by hiromik** [comment] 2017-09-20 20:32
It's the json_encode called by the **bundle** that gives that behaviour not the one from JMS since it doesn't know how to json encode the whole user object (and renders and empty user : { } object) I serialized it myself with JMS, the thing is that it gets serialized again by the bundle
