### ISSUE TITLE
error:02001003:system library:fopen:No such process 

### ISSUE THREAD

**Issue by JeremiasCaballero** [lexik/LexikJWTAuthenticationBundle#842] opened 2021-02-17 20:34 UTC
Hi, when I use the command `php bin/console lexik:jwt:generate-keypair `  for generate the key, the console shows this error
`In GenerateKeyPairCommand.php line 151:

  error:02001003:system library:fopen:No such process
`
O.S = Windows 10
PHP = 7.1
SYMFONY = 5
OPENSSL running

**Comment by chalasr** [comment] 2021-02-22 11:44
Looks like you are hitting a PHP bug that has been fixed in PHP 7.2: https://bugs.php.net/bug.php?id=60157

**Comment by NikosMetaxakis** [comment] 2021-03-03 09:52
I get the same Error,
php: 7.3.26
symfony 5.2
Windows 10

$ php bin/console lexik:jwt:generate-keypair

In GenerateKeyPairCommand.php line 156:

  error:02001003:system library:fopen:No such process  


my php version
$ php --version
PHP 7.3.26 (cli) (built: Jan  5 2021 15:10:35) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies

$ openssl version
OpenSSL 1.1.1i  8 Dec 2020

**Comment by pierre-H** [comment] 2021-03-16 10:33
Any solution ?

**Comment by Sayata** [comment] 2021-03-16 15:00
Make sure the path of the config file is set.

> set OPENSSL_CONF=\<location where cnf is available\>/openssl.cnf

**Comment by corexs** [comment] 2021-03-21 04:53
I hit this bug as well and managed to figure out a work-around. For some reason, setting the environment variable for OPENSSL_CONF does not work. Not even putenv("OPENSSL_CONF=<path to openssl.cnf>"); works.

To work-around, provide the "config" parameter when using openssl functions. For example:

$new_key = openssl_pkey_new(array(
    "private_key_bits" => 2048,
    "private_key_type" => OPENSSL_KEYTYPE_RSA,
    "config" => "<path to openssl.cnf>"
));

Hopefully someone can look into this because, wow- that was infuriating

**Comment by billal-lab** [comment] 2021-03-26 23:36
I got the same error on windows  :(

**Comment by ultimecreation** [comment] 2021-03-30 12:10
Hello i had the same issue and found this solution => https://stackoverflow.com/questions/66252709/error-system-libraryfopenno-such-process

**Comment by wizbit** [comment] 2021-04-02 09:16
I had this on Windows and it was caused by not having openssl installed.
`choco install openssl`

**Comment by joshu-aa** [comment] 2021-04-06 09:18
any update on this. same problem.

**Comment by chalasr** [comment] 2021-04-06 09:20
Seems like we can solve this with a new command option that allows passing the path to the openssl config file, right?

**Comment by joshu-aa** [comment] 2021-04-06 10:09
Hi guys got this error too maybe installing latest OpenSLL is the key because it works to me. Just go to this site and do the instruction given. https://slproweb.com/products/Win32OpenSSL.html. I HOPE I HELPED YOU GUYS <3

**Comment by DylanDelobel** [comment] 2021-04-30 13:41
Installing OpenSSL with this upper link fixed this error for me too, thanks!

**Comment by Modax59** [comment] 2021-05-06 13:14
Thanks, It worked for me

**Closed** 2021-06-14 23:34 UTC

**Comment by Skydrol** [comment] 2021-10-16 21:14
This solved this problem on windows:

https://stackoverflow.com/questions/52787456/openssl-config-failed-error02001003system-libraryfopenno-such-process-in-ap

1 - Remove environment variable OPENSSL_CONF using command
set OPENSSL_CONF=
This works but after restarting the computer the error is back again.

2 - Removed OPENSSL_CONF from Environment Variables
Go to the Windows Environment Variables and remove OPENSSL_CONF from the System variables. Save it and restart the editor and it works like a charm.

**Comment by AobDalanda** [comment] 2021-11-05 14:34
Installing OpenSSL latest version solved my issue

**Comment by MedKayed** [comment] 2023-08-18 18:54
Issue solved by:
1- install openssl last version ans set openssl path variable 
--->https://www.youtube.com/watch?v=jSkQ27sTto0

2- installed lexikJWTAuthenticationBundle:2.19 via composer
--->just run the command == composer require "lexik/jwt-authentication-bundle":2.19

3- make sure openssl extension is enabled 
--> go to your php repository (C:\wamp64\bin\php\php8.2.4 in my case)  and open php.ini file using your editor and search for extension=openssl and make sure that it is not commented out

4- make sure sodium extension is enabled 

--> go to your php repository (C:\wamp64\bin\php\php8.2.4 in my case)  and open php.ini file using your editor and search for extension=sodium and make sure that it is not commented out

**Comment by haxus01** [comment] 2023-11-22 22:00
To resolve this problem check: [ this link](https://stackoverflow.com/a/77533292/15303103)

**Comment by angelcripto** [comment] 2024-03-02 23:51
Solution: Install openssl in windows. https://slproweb.com/products/Win32OpenSSL.html

That worked for me

**Comment by Christh2022** [comment] 2024-06-10 00:51
Installing OpenSSL latest version solved my issue
Solution: Install openssl in windows. [link](https://slproweb.com/products/Win32OpenSSL.html)

**Comment by DavidBlazejczak** [comment] 2025-05-26 09:27
had the same issue just had to install openSsl and put it in the PATH variable. download it here, oh also enable sodium extension in php.ini   : 

[https://slproweb.com/products/Win32OpenSSL.html
](url)
