### ISSUE TITLE
Translate failure messages with _locale

### ISSUE THREAD

**Issue by barbhackk** [lexik/LexikJWTAuthenticationBundle#857] opened 2021-04-09 11:22 UTC
Hi,

I want to translate the message using _locale with symfony.
Here is the configuration for login_check:
```
/**
     * @Route(
     *     "/{_locale}/api/login_check",
     *     name="api_login",
     *     requirements={
     *         "_locale": "en|fr",
     *     }
     * )
     * @return JsonResponse
     */
    public function api_login(): JsonResponse
    {
        $user = $this->getUser();

        return new Response([
            'email' => $user->getEmail(),
            'roles' => $user->getRoles(),
        ]);
    }

```

When I try to call the url '/fr/api/login_check' I have an error: Call to a member function getEmail() on null.

**I think I am not using the translation as it should. I want to be able to translate according to a locale passed as a parameter in the URL**

security.yaml :
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

Thanks for your help,

Seb

**Comment by fd6130** [comment] 2021-09-18 12:44
Not sure about this but i saw this from symfony docs:

> The check_path can also be a route name (but cannot have mandatory wildcards - e.g. /login/{foo} where foo has no default value).

https://symfony.com/doc/current/security/json_login_setup.html

And see #684

**Comment by chalasr** [comment] 2021-12-05 17:41
Duplicate of https://github.com/lexik/LexikJWTAuthenticationBundle/issues/820. PR still welcome!

**Closed by chalasr** 2021-12-05 17:41 UTC
