### ISSUE TITLE
Create JWT token authentication based on specific  ip address

### ISSUE THREAD

**Issue by elangovanshanthi** [lexik/LexikJWTAuthenticationBundle#602] opened 2019-01-02 06:50 UTC
I am creating **JWT** token by using username and password, it will get the jwt token as expected, But my one of the usecase will create JWT token based on specific ip address. Let me know anyone have ideas to resovle this one?

**Comment by marioprudhomme** [comment] 2019-01-20 18:14
You could create an event listener that ads the users ip when the jwt token payload is generated, and a validation statement on the decoding end of things. See `markAsInvalid` in the link below.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md

**Comment by chalasr** [comment] 2019-01-20 18:17
Correct. Thanks for your reply @marioprudhomme.
Closing as explained, please feel free to reopen if the issue is not resolved.

**Closed by chalasr** 2019-01-20 18:17 UTC
